/* src/config_alps.h.  Generated by configure.  */
/*===========================================================================*
 * This file is part of the Abstract Library for Parallel Search (ALPS).     *
 *                                                                           *
 * ALPS is distributed under the Eclipse Public License as part of the       *
 * COIN-OR repository (http://www.coin-or.org).                              *
 *                                                                           *
 * Authors:                                                                  *
 *                                                                           *
 *          Yan Xu, Lehigh University                                        *
 *          Ted Ralphs, Lehigh University                                    *
 *                                                                           *
 * Conceptual Design:                                                        *
 *                                                                           *
 *          Yan Xu, Lehigh University                                        *
 *          Ted Ralphs, Lehigh University                                    *
 *          Laszlo Ladanyi, IBM T.J. Watson Research Center                  *
 *          Matthew Saltzman, Clemson University                             *
 *                                                                           *
 *                                                                           *
 * Copyright (C) 2001-2013, Lehigh University, Yan Xu, and Ted Ralphs.       *
 *===========================================================================*/

#ifndef __CONFIG_ALPS_H__
#define __CONFIG_ALPS_H__

/* Version number of project */
#define ALPS_VERSION "1.5.4"

/* Major Version number of project */
#define ALPS_VERSION_MAJOR 1

/* Minor Version number of project */
#define ALPS_VERSION_MINOR 5

/* Release Version number of project */
#define ALPS_VERSION_RELEASE 4

/* SVN revision of project */
#define ALPS_SVN_REV 2012

/* Define to 1 if the Mpi package is available */
/* #undef COIN_HAS_MPI */

#endif
