/* src/include/config_bcp.h.  Generated by configure.  */
#ifndef __CONFIG_BCP_H__
#define __CONFIG_BCP_H__

/* Version number of project */
#define BCP_VERSION "1.4.3"

/* Major Version number of project */
#define BCP_VERSION_MAJOR 1

/* Minor Version number of project */
#define BCP_VERSION_MINOR 4

/* Release Version number of project */
#define BCP_VERSION_RELEASE 3

/* Define to 1 if the Mpi package is available */
/* #undef COIN_HAS_MPI */

#endif
