/* src/config_blis.h.  Generated by configure.  */
/*===========================================================================*
 * This file is part of the BiCePS Linear Integer Solver (BLIS).             *
 *                                                                           *
 * BLIS is distributed under the Eclipse Public License as part of the       *
 * COIN-OR repository (http://www.coin-or.org).                              *
 *                                                                           *
 * Authors:                                                                  *
 *                                                                           *
 *          Yan Xu, Lehigh University                                        *
 *          Ted Ralphs, Lehigh University                                    *
 *                                                                           *
 * Conceptual Design:                                                        *
 *                                                                           *
 *          Yan Xu, Lehigh University                                        *
 *          Ted Ralphs, Lehigh University                                    *
 *          Laszlo Ladanyi, IBM T.J. Watson Research Center                  *
 *          Matthew Saltzman, Clemson University                             *
 *                                                                           *
 *                                                                           *
 * Copyright (C) 2001-2013, Lehigh University, Yan Xu, and Ted Ralphs.       *
 * All Rights Reserved.                                                      *
 *===========================================================================*/

#ifndef __CONFIG_BLIS_H__
#define __CONFIG_BLIS_H__

/* Version number of project */
#define BLIS_VERSION "0.94.3"

/* Major Version number of project */
#define BLIS_VERSION_MAJOR 0

/* Minor Version number of project */
#define BLIS_VERSION_MINOR 94

/* Release Version number of project */
#define BLIS_VERSION_RELEASE 3

/* SVN revision of project */
#define BLIS_SVN_REV 2012

#endif
