/* src/config_couenne.h.  Generated by configure.  */
/* src/config_couenne.h.in. */

#ifndef __CONFIG_COUENNE_H__
#define __CONFIG_COUENNE_H__

/* whether CouenneInterface is derived from Bonmin's AmplInterface */
#define COUENNEINTERFACE_FROM_ASL 1

/* Version number of project */
#define COUENNE_VERSION "0.5.6"

/* Major Version number of project */
#define COUENNE_VERSION_MAJOR 0

/* Minor Version number of project */
#define COUENNE_VERSION_MINOR 5

/* Release Version number of project */
#define COUENNE_VERSION_RELEASE 6

#endif
