/* src/config_dip.h.  Generated by configure.  */
//===========================================================================//
// This file is part of the DIP Solver Framework.                            //
//                                                                           //
// DIP is distributed under the Eclipse Public License as part of the        //
// COIN-OR repository (http://www.coin-or.org).                              //
//                                                                           //
// Author: Matthew Galati, SAS Institute Inc. (matthew.galati@sas.com)       //
//                                                                           //
// Conceptual Design: Matthew Galati, SAS Institute Inc.                     //
//                    Ted Ralphs, Lehigh University                          //
//                                                                           //
// Copyright (C) 2002-2015, Lehigh University, Matthew Galati, Ted Ralphs    //
// All Rights Reserved.                                                      //
//===========================================================================//

#ifndef __CONFIG_DIP_H__
#define __CONFIG_DIP_H__

/* Version number of project */
#define DIP_VERSION "0.92.1"

/* Major Version number of project */
#define DIP_VERSION_MAJOR 0

/* Minor Version number of project */
#define DIP_VERSION_MINOR 92

/* Release Version number of project */
#define DIP_VERSION_RELEASE 1

/* Whether we have CLP */
#define DIP_HAS_CLP 1

/* Whether we have SYMPHONY */
#define DIP_HAS_SYMPHONY 1

/* Whether we have CBC */
#define DIP_HAS_CBC 1

/* Whether we have CPLEX */
/* #undef DIP_HAS_CPX */

/* Whether we have Gurobi */
/* #undef DIP_HAS_GRB */

#endif
