/* src/DylpStdLib/config_dylp.h.  Generated by configure.  */
/* src/DylpStdLib/config_dylp.h.in. */

/* Version number of project */
#define DYLP_VERSION "1.10.3"

/* Major Version number of project */
#define DYLP_VERSION_MAJOR 1

/* Minor Version number of project */
#define DYLP_VERSION_MINOR 10

/* Release Version number of project */
#define DYLP_VERSION_RELEASE 3

/* Define to the C type whose size in bytes matches the size in bytes of the
   the C++ bool type. */
#define BOOL char
