/* src/config_flopcpp.h.  Generated by configure.  */
/* src/config_flopcpp.h.in. */

/* Version number of project */
#define FLOPCPP_VERSION "trunk"

/* Major Version number of project */
#define FLOPCPP_VERSION_MAJOR 9999

/* Minor Version number of project */
#define FLOPCPP_VERSION_MINOR 9999

/* Release Version number of project */
#define FLOPCPP_VERSION_RELEASE 9999
