/* src/config_os.h.  Generated by configure.  */
/* src/config_os.h.in. */

#ifndef __CONFIG_OS_H__
#define __CONFIG_OS_H__

/* Version number of project */
#define OS_VERSION "2.10.1"

/* Major Version number of project */
#define OS_VERSION_MAJOR 2

/* Minor Version number of project */
#define OS_VERSION_MINOR 10

/* Release Version number of project */
#define OS_VERSION_RELEASE 1

/* Define to 1 if OS uses CppAD */
#define OS_HAS_CPPAD 1

/* Define to 1 if OS uses Ipopt */
#define OS_HAS_IPOPT 1

/* Define to 1 if OS uses Bonmin */
#define OS_HAS_BONMIN 1

/* Define to 1 if OS uses Couenne */
#define OS_HAS_COUENNE 1

/* Define to 1 if OS uses SYMPHONY */
#define OS_HAS_SYMPHONY 1

/* Define to 1 if OS uses VOL */
#define OS_HAS_VOL 1

/* Define to 1 if OS uses ASL */
#define OS_HAS_ASL 1

/* Define to 1 if OS uses DyLP */
#define OS_HAS_DYLP 1

/* Define to 1 if OS uses Glpk */
#define OS_HAS_GLPK 1

#endif /* __CONFIG_OS_H__ */
