/* src/config_smi.h.  Generated by configure.  */
#ifndef __CONFIG_SMI_H__
#define __CONFIG_SMI_H__

/* Version number of project */
#define SMI_VERSION "0.95.2"

/* Major Version number of project */
#define SMI_VERSION_MAJOR 0

/* Minor Version number of project */
#define SMI_VERSION_MINOR 95

/* Release Version number of project */
#define SMI_VERSION_RELEASE 2

#endif
